SYNTHDEFS = playSampleStereo playSampleMono recordSampleStereo bell crotale dx fmtanh ghost kick marimba moog piano prophet snare

all: $(SYNTHDEFS)

$(SYNTHDEFS):
	cp ~/'Library/Application Support/SuperCollider/synthdefs'/$@.scsyndef compiled

